#!/bin/bash

#SBATCH --job-name=fastqc
#SBATCH -A ecoevo283
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load fastqc/0.11.9

fastqc -t 8 /pub/etom2/EE283/EE283/Week3/DNAseq/trim/ADL06-trimmed_1P.fq.gz /pub/etom2/EE283/EE283/Week3/DNAseq/trim/ADL06-trimmed_2P.fq.gz -o /pub/etom2/EE283/EE283/Week3/DNAseq/trim/fastqc

mkdir /pub/etom2/EE283/EE283/Week3/DNAseq/trim/fastqc/html

mv /pub/etom2/EE283/EE283/Week3/DNAseq/trim/fastqc/*.html /pub/etom2/EE283/EE283/Week3/DNAseq/trim/fastqc/html

module unload fastqc/0.11.9
