#!/bin/bash

#SBATCH --job-name=trim
#SBATCH -A etom2
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load trimmomatic/0.39

FPATH='/pub/etom2/iPSC-RPE_RNA-Seq/raw';
OPATH='/pub/etom2/iPSC-RPE_RNA-Seq/processed/trim';
ADPATH='/opt/apps/trimmomatic/0.39/adapters/TruSeq3-PE-2.fa';

java -jar /opt/apps/trimmomatic/0.39/trimmomatic-0.39.jar PE -threads 8 -phred33 \
	-baseout ${OPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG-trimmed.fq.gz \
	${FPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG-READ1-Sequences.txt.gz \
	${FPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG-READ2-Sequences.txt.gz \
	ILLUMINACLIP:${ADPATH}:2:30:10 \
	SLIDINGWINDOW:4:15 \
	MINLEN:20 \

module unload trimmomatic/0.39
