#!/bin/bash
  
#SBATCH --job-name=ATACseq_peakcalling
#SBATCH -A ecoevo283
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load samtools/1.15.1
module load bedtools2/2.30.0 
module load macs/2.2.7.1  

samtools merge -o A4_ED_combined.bam A4_ED_2.dedup.bam A4_ED_3.dedup.bam A4_ED_4.dedup.bam \
bedtools bamtobed -i A4_ED_combined.bam | awk -F $'\t' 'BEGIN {OFS = FS}{ if ($6 == "+") {$2 = $2 + 4} else if ($6 == "-") {$3 = $3 - 5} print $0}' > A4_ED_combined.tn5.bed \
macs2 callpeak -t A4_ED_combined.tn5.bed -n A4_ED_combined -f BED -g mm -q 0.01 --nomodel --shift -75 --extsize 150 --call-summits --keep-dup all -B \

module unload samtools/1.15.1
module unload bedtools2/2.30.0 
module unload macs/2.2.7.1  
