#!/bin/bash
#SBATCH --job-name=hisat2
#SBATCH -A etom2
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=1
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load hisat2/2.2.1
module load samtools/1.10

IPATH='/pub/etom2/iPSC-RPE_RNA-Seq/processed/trim';
OPATH='/pub/etom2/iPSC-RPE_RNA-Seq/processed/align';
SPATH='/pub/etom2/iPSC-RPE_RNA-Seq/processed/align/alignment_summary';
RPATH='/pub/etom2/iPSC-RPE_RNA-Seq/processed/align/grch38_genome/grch38/genome';

hisat2 -p 8 -t --qc-filter  --rna-strandness RF \
--summary-file ${SPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG.align \
-x ${RPATH} --dta-cufflinks \
-1 ${IPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG-trimmed_1P.fq.gz \
-2 ${IPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG-trimmed_2P.fq.gz | 
samtools view -@ 8 -bS -> ${OPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG_align.bam

samtools sort -@ 8 -o ${OPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG_sorted.bam ${OPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG_align.bam
samtools index -@ 8 ${OPATH}/nR238-L1-G2-P22-TCAACGAG-GGTTGACG_sorted.bam \

module unload hisat2/2.2.1
