#!/bin/bash
  
#SBATCH --job-name=callSNPs
#SBATCH -A ecoevo283
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --array=5-7
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load java/1.8.0
module load gatk/4.1.9.0

ref="/pub/etom2/EE283/EE283/Week3/DNAseq/align/dmel-all-chromosome-r6.49.fasta"
mychr=`head -n $SLURM_ARRAY_TASK_ID chrome.names.txt | tail -n 1`

/opt/apps/gatk/4.1.9.0/gatk --java-options "-Xmx3g" GenotypeGVCFs \
-R $ref -V allsample.g.vcf.gz --intervals $mychr \
-stand-call-conf 5 -O result.${mychr}.vcf.gz

module unload java/1.8.0
module unload gatk/4.1.9.0

