#!/bin/bash
  
#SBATCH --job-name=DNAseq_merge_vcf
#SBATCH -A ecoevo283
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --array=1-4
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load java/1.8.0
module load gatk/4.2.6.1

ref="/pub/etom2/EE283/EE283/Week3/DNAseq/align/dmel-all-chromosome-r6.49.fasta"

java -jar /opt/apps/gatk/4.2.6.1/gatk-package-4.2.6.1-local.jar CombineGVCFs -R $ref $(printf -- '-V %s ' *.g.vcf.gz) -O allsample.g.vcf.gz

module unload java/1.8.0
module unload gatk/4.2.6.1
