#!/bin/bash
  
#SBATCH --job-name=merge_resultvcfs
#SBATCH -A ecoevo283
#SBATCH -p standard
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --error=slurm-%x.%j.err
#SBATCH --output=slurm-%x.%j.out

module load picard-tools/2.27.1

java -jar /opt/apps/picard-tools/2.27.1/picard.jar MergeVcfs \
$(printf 'I=%s ' result.*.vcf.gz) O=all_variants.vcf.gz

module unload picard-tools/2.27.1
